FROM arm64v8/node:14.17.5-alpine3.14

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm ci --only=production

COPY . .

RUN mkdir logs
RUN touch ./logs/error.log
RUN touch ./logs/combined.log

EXPOSE 3000
CMD ["npm", "run", "start"]

