FROM node:14.15.4-alpine

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm ci --only=production

COPY . .

RUN mkdir logs
RUN touch ./logs/error.log
RUN touch ./logs/info.log

EXPOSE 3000
CMD ["npm", "run", "start"]
