version: '3.8'

services:
  
  nodemailer:  
    image: registry.gitlab.com/im-technologies/mail-server:latest
    restart: unless-stopped
    ports:
    - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./templates:/usr/src/app/templates
      - ./logs:/usr/src/app/logs