// const { Middleware } = require('swagger-express-middleware');
const http = require('http');
const fs = require('fs');
const path = require('path');
const swaggerUI = require('swagger-ui-express');
const jsYaml = require('js-yaml');
const express = require('express');
const cors = require('cors');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const { OpenApiValidator } = require('express-openapi-validator');
const dotenv = require('dotenv');
const logger = require('./logger');
const config = require('./config');

dotenv.config();

class ExpressServer {
  constructor(port, openApiYaml) {
    this.port = port;
    this.app = express();
    this.openApiPath = openApiYaml;
    try {
      this.schema = jsYaml.safeLoad(fs.readFileSync(openApiYaml));
    } catch (e) {
      logger.error('failed to start Express Server', e.message);
    }
    this.setupMiddleware();
  }

  setupMiddleware() {
    // this.setupAllowedMedia();
    this.app.use(cors());
    this.app.use(bodyParser.json({ limit: `${process.env.MAX_FILE_SIZE}MB` || '14MB' }));
    this.app.use(express.json());
    this.app.use(express.urlencoded({ extended: false }));
    this.app.use(cookieParser());
    this.app.use(express.static(path.join(__dirname, 'public')));
    // Send the openapi document *AS GENERATED BY THE GENERATOR*
    this.app.get('/openapi', (req, res) => res.sendFile((path.join(__dirname, 'api', 'openapi.yaml'))));
    // View the openapi document in a visual interface. Should be able to test from this page
    this.app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(this.schema));
    // Test page to test if server is running correctly
    this.app.get('/', (req, res) => {
      res.send(`Nodemailer Service - Status OK - Mode: ${process.env.ENV}`);
    });
    // CORS Settings
    let origins = [];
    if (process.env.ENV.toUpperCase() === 'PROD') origins = [process.env.SERVER_DOMAIN];
    if (process.env.ENV.toUpperCase() === 'DEV') origins = ['https://localhost:3000', 'https://127.0.0.1:80', 'http://localhost:3000', 'http://127.0.0.1:80'];
    this.app.use(cors({
      credentials: true,
      origin: origins,
      exposedHeaders: ['Accept-Ranges', 'Content-Encoding', 'Content-Length', 'Content-Range'],
      allowedHeaders: ['Content-Type', 'Authorization', 'Accepts', 'Set-Cookie', 'Cookie', 'Range'],
    }));
  }

  launch() {
    new OpenApiValidator({
      apiSpec: this.openApiPath,
      validateResponses: false,
      validateRequests: true,
      operationHandlers: path.join(__dirname),
      fileUploader: { dest: config.FILE_UPLOAD_PATH },
    }).install(this.app)
      .catch((e) => console.log(e))
      .then(() => {
        // eslint-disable-next-line no-unused-vars
        this.app.use((err, req, res, next) => {
          // format errors
          res.status(err.status || 500).json({
            message: err.message || err,
            errors: err.errors || '',
          });
        });

        http.createServer(this.app).listen(this.port);
        console.log(`Listening on port ${this.port}`);
      });
  }

  async close() {
    if (this.server !== undefined) {
      await this.server.close();
      console.log(`Server on port ${this.port} shut down`);
    }
  }
}

module.exports = ExpressServer;
