FROM node:22-alpine

ARG DEFAULT_PORT=3000

ENV PORT $DEFAULT_PORT

# Create app directory
WORKDIR /usr/src/app

# Create the required folders
RUN mkdir -p logs uploaded_files tmp

# Install app dependencies
COPY package*.json ./

# Install dependencies (only production for final image)
RUN npm ci --only=production

# Bundle app source
COPY . .

# Run server
EXPOSE $PORT
CMD [ "npm", "run", "start" ]
