version: '3.8'

services:
  
  mailer:  
    image: ghcr.io/giamboscaro/mail-service:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./templates:/usr/src/app/templates
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "--tries=1", "http://localhost:3000/"]
      interval: 2s
      timeout: 5s
      retries: 10
